name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.10", "2.13.1"]
        scalajsversion: ["1.x", "0.6.x"]
        include:
          - scalaversion: "2.10.7"
            scalajsversion: "0.6.x"
    env:
      SCALAJS_VERSION: "${{ matrix.scalajsversion == '0.6.x' && '0.6.31' || '' }}"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Scalastyle
        run: sbt "++${{ matrix.scalaversion }}" root/scalastyle testSuiteJVM/scalastyle testSuiteJVM/test:scalastyle testSuiteJS/scalastyle testSuiteJS/test:scalastyle
      - name: Test JVM
        run: sbt "++${{ matrix.scalaversion }}" testSuiteJVM/test
      - name: Test JS
        run: sbt "++${{ matrix.scalaversion }}" testSuiteJS/test
      - name: Test JS fullOpt
        run: sbt "++${{ matrix.scalaversion }}" 'set scalaJSStage in Global := FullOptStage' testSuiteJS/test
      - name: Test publish
        run: sbt "++${{ matrix.scalaversion }}" publishLocal
